# - name: Load Maven
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: maven

# - name: Install MySQL Client
#   ansible.builtin.dnf:
#     name: mysql
#     state: installed

# - name: Load Schema
#   ansible.builtin.shell: mysql -h mysql-dev.gurudevops4.online -uroot -p${MYSQL_ROOT_PASSWORD} < /app/db/schema.sql
#   environment:
#     MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"

#   loop:
#     - schema
#     - app-user
#     - master-data

- name: Load Docker
  ansible.builtin.import_role:
    name: common
    tasks_from: docker